title: "ZooKage"
description: >-
  Hadoop on Kubernetes on Docker Desktop
domain: zookage.github.io
url: "https://zookage.github.io/"
twitter_username: okumin
github_username: zookage

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
