title: "ZooKage"
description: >-
  Hadoop on Kubernetes on Docker Desktop
domain: zookage.github.io
url: "https://zookage.github.io/"
github_username: zookage

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
- docs/quick-start.md
- docs/tools.md
- docs/configuration.md
- docs/build-image.md

google_analytics: G-LL5EPQBZZT
